# Change these first
owner: littleBanshee # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Univ Home
    url: $UNIV_HOME
    maxResponseTime: 3350
    expectedStatusCodes:
    - 200
    
  - name: Univ SSO
    url: $UNIV_SSO
    maxResponseTime: 3350
    expectedStatusCodes:
    - 200
    
  - name: Univ Shibboleth
    url: $UNIV_SHIBBOLETH
    maxResponseTime: 3350
    expectedStatusCodes:
    - 200
    
  - name: Univ IMAPS
    check: "tcp-ping"
    url: $UNIV_MAIL
    port: 993
    
  - name: Univ SMTPS
    check: "tcp-ping"
    url: $UNIV_MAIL
    port: 465
    
  - name: Univ VPN1
    check: "tcp-ping"
    url: $UNIV_VPN1
    port: 443
    
  - name: Univ VPN2
    url: $UNIV_VPN2
    maxResponseTime: 3350
    
  - name: Univ VPN
    check: "tcp-ping"
    url: $UNIV_VPN
    port: 443
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# workflowSchedule:
#   graphs: "0 0 * * *"
#   responseTime: "0 23 * * *"
#   staticSite: "0 1 * * *"
#   summary: "0 0 * * *"
#   updateTemplate: "0 0 * * *"
#   updates: "0 3 * * *"
#   uptime: "*/5 * * * *"
